version: "3"

services:
  chrome:
    image: docker.io/zenika/alpine-chrome:latest
    container_name: chrome
    network_mode: host
    command: --no-sandbox --remote-debugging-port=9222
    restart: unless-stopped
