version: "3"
services:
  headless-chrome:
    image: docker.io/zenika/alpine-chrome
    container_name: headless-chrome
    ports:
      - "9222:9222"
    command: >
      --no-sandbox
      --headless
      --disable-gpu
      --remote-debugging-address=0.0.0.0
      --remote-debugging-port=9222
    restart: unless-stopped
