version: "3"
services:
  headless-chrome:
    image: docker.io/zenika/alpine-chrome
    container_name: headless-chrome
    network_mode: "host"
    command: >
      --no-sandbox
      --headless
      --remote-debugging-port=9222
      --user-data-dir=/home/chrome/data
    restart: unless-stopped
